// flow-typed signature: 2a6f8fdd6fba43899a6e4b32c73a27a8
// flow-typed version: <<STUB>>/aframe_v^0.7.0/flow_v0.54.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'aframe'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'aframe' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'aframe/build/aframe-core' {
  declare module.exports: any;
}

declare module 'aframe/build/aframe' {
  declare module.exports: any;
}

declare module 'aframe/dist/aframe-master' {
  declare module.exports: any;
}

declare module 'aframe/gh-pages/dist/aframe-master' {
  declare module.exports: any;
}

declare module 'aframe/gh-pages/dist/aframe-master.min' {
  declare module.exports: any;
}

declare module 'aframe/gh-pages/dist/aframe-v0.7.0' {
  declare module.exports: any;
}

declare module 'aframe/gh-pages/dist/aframe-v0.7.0.min' {
  declare module.exports: any;
}

declare module 'aframe/scripts/budo' {
  declare module.exports: any;
}

declare module 'aframe/scripts/docsLint' {
  declare module.exports: any;
}

declare module 'aframe/scripts/preghpages' {
  declare module.exports: any;
}

declare module 'aframe/scripts/release' {
  declare module.exports: any;
}

declare module 'aframe/scripts/updateVersionLog' {
  declare module.exports: any;
}

declare module 'aframe/src/components/camera' {
  declare module.exports: any;
}

declare module 'aframe/src/components/collada-model' {
  declare module.exports: any;
}

declare module 'aframe/src/components/cursor' {
  declare module.exports: any;
}

declare module 'aframe/src/components/daydream-controls' {
  declare module.exports: any;
}

declare module 'aframe/src/components/gearvr-controls' {
  declare module.exports: any;
}

declare module 'aframe/src/components/geometry' {
  declare module.exports: any;
}

declare module 'aframe/src/components/gltf-model' {
  declare module.exports: any;
}

declare module 'aframe/src/components/hand-controls' {
  declare module.exports: any;
}

declare module 'aframe/src/components/index' {
  declare module.exports: any;
}

declare module 'aframe/src/components/laser-controls' {
  declare module.exports: any;
}

declare module 'aframe/src/components/light' {
  declare module.exports: any;
}

declare module 'aframe/src/components/line' {
  declare module.exports: any;
}

declare module 'aframe/src/components/link' {
  declare module.exports: any;
}

declare module 'aframe/src/components/look-controls' {
  declare module.exports: any;
}

declare module 'aframe/src/components/material' {
  declare module.exports: any;
}

declare module 'aframe/src/components/obj-model' {
  declare module.exports: any;
}

declare module 'aframe/src/components/oculus-touch-controls' {
  declare module.exports: any;
}

declare module 'aframe/src/components/position' {
  declare module.exports: any;
}

declare module 'aframe/src/components/raycaster' {
  declare module.exports: any;
}

declare module 'aframe/src/components/rotation' {
  declare module.exports: any;
}

declare module 'aframe/src/components/scale' {
  declare module.exports: any;
}

declare module 'aframe/src/components/scene/debug' {
  declare module.exports: any;
}

declare module 'aframe/src/components/scene/embedded' {
  declare module.exports: any;
}

declare module 'aframe/src/components/scene/fog' {
  declare module.exports: any;
}

declare module 'aframe/src/components/scene/inspector' {
  declare module.exports: any;
}

declare module 'aframe/src/components/scene/keyboard-shortcuts' {
  declare module.exports: any;
}

declare module 'aframe/src/components/scene/pool' {
  declare module.exports: any;
}

declare module 'aframe/src/components/scene/screenshot' {
  declare module.exports: any;
}

declare module 'aframe/src/components/scene/stats' {
  declare module.exports: any;
}

declare module 'aframe/src/components/scene/vr-mode-ui' {
  declare module.exports: any;
}

declare module 'aframe/src/components/shadow' {
  declare module.exports: any;
}

declare module 'aframe/src/components/sound' {
  declare module.exports: any;
}

declare module 'aframe/src/components/text' {
  declare module.exports: any;
}

declare module 'aframe/src/components/tracked-controls' {
  declare module.exports: any;
}

declare module 'aframe/src/components/visible' {
  declare module.exports: any;
}

declare module 'aframe/src/components/vive-controls' {
  declare module.exports: any;
}

declare module 'aframe/src/components/wasd-controls' {
  declare module.exports: any;
}

declare module 'aframe/src/components/windows-motion-controls' {
  declare module.exports: any;
}

declare module 'aframe/src/constants/animation' {
  declare module.exports: any;
}

declare module 'aframe/src/constants/index' {
  declare module.exports: any;
}

declare module 'aframe/src/constants/keyboardevent' {
  declare module.exports: any;
}

declare module 'aframe/src/core/a-animation' {
  declare module.exports: any;
}

declare module 'aframe/src/core/a-assets' {
  declare module.exports: any;
}

declare module 'aframe/src/core/a-cubemap' {
  declare module.exports: any;
}

declare module 'aframe/src/core/a-entity' {
  declare module.exports: any;
}

declare module 'aframe/src/core/a-mixin' {
  declare module.exports: any;
}

declare module 'aframe/src/core/a-node' {
  declare module.exports: any;
}

declare module 'aframe/src/core/a-register-element' {
  declare module.exports: any;
}

declare module 'aframe/src/core/component' {
  declare module.exports: any;
}

declare module 'aframe/src/core/geometry' {
  declare module.exports: any;
}

declare module 'aframe/src/core/propertyTypes' {
  declare module.exports: any;
}

declare module 'aframe/src/core/scene/a-scene' {
  declare module.exports: any;
}

declare module 'aframe/src/core/scene/metaTags' {
  declare module.exports: any;
}

declare module 'aframe/src/core/scene/postMessage' {
  declare module.exports: any;
}

declare module 'aframe/src/core/scene/scenes' {
  declare module.exports: any;
}

declare module 'aframe/src/core/scene/wakelock' {
  declare module.exports: any;
}

declare module 'aframe/src/core/schema' {
  declare module.exports: any;
}

declare module 'aframe/src/core/shader' {
  declare module.exports: any;
}

declare module 'aframe/src/core/system' {
  declare module.exports: any;
}

declare module 'aframe/src/extras/components/index' {
  declare module.exports: any;
}

declare module 'aframe/src/extras/components/pivot' {
  declare module.exports: any;
}

declare module 'aframe/src/extras/primitives/getMeshMixin' {
  declare module.exports: any;
}

declare module 'aframe/src/extras/primitives/index' {
  declare module.exports: any;
}

declare module 'aframe/src/extras/primitives/primitives' {
  declare module.exports: any;
}

declare module 'aframe/src/extras/primitives/primitives/a-camera' {
  declare module.exports: any;
}

declare module 'aframe/src/extras/primitives/primitives/a-collada-model' {
  declare module.exports: any;
}

declare module 'aframe/src/extras/primitives/primitives/a-cursor' {
  declare module.exports: any;
}

declare module 'aframe/src/extras/primitives/primitives/a-curvedimage' {
  declare module.exports: any;
}

declare module 'aframe/src/extras/primitives/primitives/a-gltf-model' {
  declare module.exports: any;
}

declare module 'aframe/src/extras/primitives/primitives/a-image' {
  declare module.exports: any;
}

declare module 'aframe/src/extras/primitives/primitives/a-light' {
  declare module.exports: any;
}

declare module 'aframe/src/extras/primitives/primitives/a-link' {
  declare module.exports: any;
}

declare module 'aframe/src/extras/primitives/primitives/a-obj-model' {
  declare module.exports: any;
}

declare module 'aframe/src/extras/primitives/primitives/a-sky' {
  declare module.exports: any;
}

declare module 'aframe/src/extras/primitives/primitives/a-sound' {
  declare module.exports: any;
}

declare module 'aframe/src/extras/primitives/primitives/a-text' {
  declare module.exports: any;
}

declare module 'aframe/src/extras/primitives/primitives/a-video' {
  declare module.exports: any;
}

declare module 'aframe/src/extras/primitives/primitives/a-videosphere' {
  declare module.exports: any;
}

declare module 'aframe/src/extras/primitives/primitives/meshPrimitives' {
  declare module.exports: any;
}

declare module 'aframe/src/geometries/box' {
  declare module.exports: any;
}

declare module 'aframe/src/geometries/circle' {
  declare module.exports: any;
}

declare module 'aframe/src/geometries/cone' {
  declare module.exports: any;
}

declare module 'aframe/src/geometries/cylinder' {
  declare module.exports: any;
}

declare module 'aframe/src/geometries/dodecahedron' {
  declare module.exports: any;
}

declare module 'aframe/src/geometries/icosahedron' {
  declare module.exports: any;
}

declare module 'aframe/src/geometries/index' {
  declare module.exports: any;
}

declare module 'aframe/src/geometries/octahedron' {
  declare module.exports: any;
}

declare module 'aframe/src/geometries/plane' {
  declare module.exports: any;
}

declare module 'aframe/src/geometries/ring' {
  declare module.exports: any;
}

declare module 'aframe/src/geometries/sphere' {
  declare module.exports: any;
}

declare module 'aframe/src/geometries/tetrahedron' {
  declare module.exports: any;
}

declare module 'aframe/src/geometries/torus' {
  declare module.exports: any;
}

declare module 'aframe/src/geometries/torusKnot' {
  declare module.exports: any;
}

declare module 'aframe/src/geometries/triangle' {
  declare module.exports: any;
}

declare module 'aframe/src/index' {
  declare module.exports: any;
}

declare module 'aframe/src/lib/rStatsAframe' {
  declare module.exports: any;
}

declare module 'aframe/src/lib/three' {
  declare module.exports: any;
}

declare module 'aframe/src/shaders/flat' {
  declare module.exports: any;
}

declare module 'aframe/src/shaders/index' {
  declare module.exports: any;
}

declare module 'aframe/src/shaders/ios10hls' {
  declare module.exports: any;
}

declare module 'aframe/src/shaders/msdf' {
  declare module.exports: any;
}

declare module 'aframe/src/shaders/sdf' {
  declare module.exports: any;
}

declare module 'aframe/src/shaders/standard' {
  declare module.exports: any;
}

declare module 'aframe/src/systems/camera' {
  declare module.exports: any;
}

declare module 'aframe/src/systems/geometry' {
  declare module.exports: any;
}

declare module 'aframe/src/systems/index' {
  declare module.exports: any;
}

declare module 'aframe/src/systems/light' {
  declare module.exports: any;
}

declare module 'aframe/src/systems/material' {
  declare module.exports: any;
}

declare module 'aframe/src/systems/shadow' {
  declare module.exports: any;
}

declare module 'aframe/src/systems/tracked-controls' {
  declare module.exports: any;
}

declare module 'aframe/src/utils/bind' {
  declare module.exports: any;
}

declare module 'aframe/src/utils/coordinates' {
  declare module.exports: any;
}

declare module 'aframe/src/utils/debug' {
  declare module.exports: any;
}

declare module 'aframe/src/utils/device' {
  declare module.exports: any;
}

declare module 'aframe/src/utils/entity' {
  declare module.exports: any;
}

declare module 'aframe/src/utils/forceCanvasResizeSafariMobile' {
  declare module.exports: any;
}

declare module 'aframe/src/utils/index' {
  declare module.exports: any;
}

declare module 'aframe/src/utils/material' {
  declare module.exports: any;
}

declare module 'aframe/src/utils/src-loader' {
  declare module.exports: any;
}

declare module 'aframe/src/utils/styleParser' {
  declare module.exports: any;
}

declare module 'aframe/src/utils/tracked-controls' {
  declare module.exports: any;
}

declare module 'aframe/vendor/rStats.extras' {
  declare module.exports: any;
}

declare module 'aframe/vendor/rStats' {
  declare module.exports: any;
}

declare module 'aframe/vendor/VRControls' {
  declare module.exports: any;
}

declare module 'aframe/vendor/VREffect' {
  declare module.exports: any;
}

declare module 'aframe/vendor/wakelock/util' {
  declare module.exports: any;
}

declare module 'aframe/vendor/wakelock/wakelock' {
  declare module.exports: any;
}

// Filename aliases
declare module 'aframe/build/aframe-core.js' {
  declare module.exports: $Exports<'aframe/build/aframe-core'>;
}
declare module 'aframe/build/aframe.js' {
  declare module.exports: $Exports<'aframe/build/aframe'>;
}
declare module 'aframe/dist/aframe-master.js' {
  declare module.exports: $Exports<'aframe/dist/aframe-master'>;
}
declare module 'aframe/gh-pages/dist/aframe-master.js' {
  declare module.exports: $Exports<'aframe/gh-pages/dist/aframe-master'>;
}
declare module 'aframe/gh-pages/dist/aframe-master.min.js' {
  declare module.exports: $Exports<'aframe/gh-pages/dist/aframe-master.min'>;
}
declare module 'aframe/gh-pages/dist/aframe-v0.7.0.js' {
  declare module.exports: $Exports<'aframe/gh-pages/dist/aframe-v0.7.0'>;
}
declare module 'aframe/gh-pages/dist/aframe-v0.7.0.min.js' {
  declare module.exports: $Exports<'aframe/gh-pages/dist/aframe-v0.7.0.min'>;
}
declare module 'aframe/scripts/budo.js' {
  declare module.exports: $Exports<'aframe/scripts/budo'>;
}
declare module 'aframe/scripts/docsLint.js' {
  declare module.exports: $Exports<'aframe/scripts/docsLint'>;
}
declare module 'aframe/scripts/preghpages.js' {
  declare module.exports: $Exports<'aframe/scripts/preghpages'>;
}
declare module 'aframe/scripts/release.js' {
  declare module.exports: $Exports<'aframe/scripts/release'>;
}
declare module 'aframe/scripts/updateVersionLog.js' {
  declare module.exports: $Exports<'aframe/scripts/updateVersionLog'>;
}
declare module 'aframe/src/components/camera.js' {
  declare module.exports: $Exports<'aframe/src/components/camera'>;
}
declare module 'aframe/src/components/collada-model.js' {
  declare module.exports: $Exports<'aframe/src/components/collada-model'>;
}
declare module 'aframe/src/components/cursor.js' {
  declare module.exports: $Exports<'aframe/src/components/cursor'>;
}
declare module 'aframe/src/components/daydream-controls.js' {
  declare module.exports: $Exports<'aframe/src/components/daydream-controls'>;
}
declare module 'aframe/src/components/gearvr-controls.js' {
  declare module.exports: $Exports<'aframe/src/components/gearvr-controls'>;
}
declare module 'aframe/src/components/geometry.js' {
  declare module.exports: $Exports<'aframe/src/components/geometry'>;
}
declare module 'aframe/src/components/gltf-model.js' {
  declare module.exports: $Exports<'aframe/src/components/gltf-model'>;
}
declare module 'aframe/src/components/hand-controls.js' {
  declare module.exports: $Exports<'aframe/src/components/hand-controls'>;
}
declare module 'aframe/src/components/index.js' {
  declare module.exports: $Exports<'aframe/src/components/index'>;
}
declare module 'aframe/src/components/laser-controls.js' {
  declare module.exports: $Exports<'aframe/src/components/laser-controls'>;
}
declare module 'aframe/src/components/light.js' {
  declare module.exports: $Exports<'aframe/src/components/light'>;
}
declare module 'aframe/src/components/line.js' {
  declare module.exports: $Exports<'aframe/src/components/line'>;
}
declare module 'aframe/src/components/link.js' {
  declare module.exports: $Exports<'aframe/src/components/link'>;
}
declare module 'aframe/src/components/look-controls.js' {
  declare module.exports: $Exports<'aframe/src/components/look-controls'>;
}
declare module 'aframe/src/components/material.js' {
  declare module.exports: $Exports<'aframe/src/components/material'>;
}
declare module 'aframe/src/components/obj-model.js' {
  declare module.exports: $Exports<'aframe/src/components/obj-model'>;
}
declare module 'aframe/src/components/oculus-touch-controls.js' {
  declare module.exports: $Exports<'aframe/src/components/oculus-touch-controls'>;
}
declare module 'aframe/src/components/position.js' {
  declare module.exports: $Exports<'aframe/src/components/position'>;
}
declare module 'aframe/src/components/raycaster.js' {
  declare module.exports: $Exports<'aframe/src/components/raycaster'>;
}
declare module 'aframe/src/components/rotation.js' {
  declare module.exports: $Exports<'aframe/src/components/rotation'>;
}
declare module 'aframe/src/components/scale.js' {
  declare module.exports: $Exports<'aframe/src/components/scale'>;
}
declare module 'aframe/src/components/scene/debug.js' {
  declare module.exports: $Exports<'aframe/src/components/scene/debug'>;
}
declare module 'aframe/src/components/scene/embedded.js' {
  declare module.exports: $Exports<'aframe/src/components/scene/embedded'>;
}
declare module 'aframe/src/components/scene/fog.js' {
  declare module.exports: $Exports<'aframe/src/components/scene/fog'>;
}
declare module 'aframe/src/components/scene/inspector.js' {
  declare module.exports: $Exports<'aframe/src/components/scene/inspector'>;
}
declare module 'aframe/src/components/scene/keyboard-shortcuts.js' {
  declare module.exports: $Exports<'aframe/src/components/scene/keyboard-shortcuts'>;
}
declare module 'aframe/src/components/scene/pool.js' {
  declare module.exports: $Exports<'aframe/src/components/scene/pool'>;
}
declare module 'aframe/src/components/scene/screenshot.js' {
  declare module.exports: $Exports<'aframe/src/components/scene/screenshot'>;
}
declare module 'aframe/src/components/scene/stats.js' {
  declare module.exports: $Exports<'aframe/src/components/scene/stats'>;
}
declare module 'aframe/src/components/scene/vr-mode-ui.js' {
  declare module.exports: $Exports<'aframe/src/components/scene/vr-mode-ui'>;
}
declare module 'aframe/src/components/shadow.js' {
  declare module.exports: $Exports<'aframe/src/components/shadow'>;
}
declare module 'aframe/src/components/sound.js' {
  declare module.exports: $Exports<'aframe/src/components/sound'>;
}
declare module 'aframe/src/components/text.js' {
  declare module.exports: $Exports<'aframe/src/components/text'>;
}
declare module 'aframe/src/components/tracked-controls.js' {
  declare module.exports: $Exports<'aframe/src/components/tracked-controls'>;
}
declare module 'aframe/src/components/visible.js' {
  declare module.exports: $Exports<'aframe/src/components/visible'>;
}
declare module 'aframe/src/components/vive-controls.js' {
  declare module.exports: $Exports<'aframe/src/components/vive-controls'>;
}
declare module 'aframe/src/components/wasd-controls.js' {
  declare module.exports: $Exports<'aframe/src/components/wasd-controls'>;
}
declare module 'aframe/src/components/windows-motion-controls.js' {
  declare module.exports: $Exports<'aframe/src/components/windows-motion-controls'>;
}
declare module 'aframe/src/constants/animation.js' {
  declare module.exports: $Exports<'aframe/src/constants/animation'>;
}
declare module 'aframe/src/constants/index.js' {
  declare module.exports: $Exports<'aframe/src/constants/index'>;
}
declare module 'aframe/src/constants/keyboardevent.js' {
  declare module.exports: $Exports<'aframe/src/constants/keyboardevent'>;
}
declare module 'aframe/src/core/a-animation.js' {
  declare module.exports: $Exports<'aframe/src/core/a-animation'>;
}
declare module 'aframe/src/core/a-assets.js' {
  declare module.exports: $Exports<'aframe/src/core/a-assets'>;
}
declare module 'aframe/src/core/a-cubemap.js' {
  declare module.exports: $Exports<'aframe/src/core/a-cubemap'>;
}
declare module 'aframe/src/core/a-entity.js' {
  declare module.exports: $Exports<'aframe/src/core/a-entity'>;
}
declare module 'aframe/src/core/a-mixin.js' {
  declare module.exports: $Exports<'aframe/src/core/a-mixin'>;
}
declare module 'aframe/src/core/a-node.js' {
  declare module.exports: $Exports<'aframe/src/core/a-node'>;
}
declare module 'aframe/src/core/a-register-element.js' {
  declare module.exports: $Exports<'aframe/src/core/a-register-element'>;
}
declare module 'aframe/src/core/component.js' {
  declare module.exports: $Exports<'aframe/src/core/component'>;
}
declare module 'aframe/src/core/geometry.js' {
  declare module.exports: $Exports<'aframe/src/core/geometry'>;
}
declare module 'aframe/src/core/propertyTypes.js' {
  declare module.exports: $Exports<'aframe/src/core/propertyTypes'>;
}
declare module 'aframe/src/core/scene/a-scene.js' {
  declare module.exports: $Exports<'aframe/src/core/scene/a-scene'>;
}
declare module 'aframe/src/core/scene/metaTags.js' {
  declare module.exports: $Exports<'aframe/src/core/scene/metaTags'>;
}
declare module 'aframe/src/core/scene/postMessage.js' {
  declare module.exports: $Exports<'aframe/src/core/scene/postMessage'>;
}
declare module 'aframe/src/core/scene/scenes.js' {
  declare module.exports: $Exports<'aframe/src/core/scene/scenes'>;
}
declare module 'aframe/src/core/scene/wakelock.js' {
  declare module.exports: $Exports<'aframe/src/core/scene/wakelock'>;
}
declare module 'aframe/src/core/schema.js' {
  declare module.exports: $Exports<'aframe/src/core/schema'>;
}
declare module 'aframe/src/core/shader.js' {
  declare module.exports: $Exports<'aframe/src/core/shader'>;
}
declare module 'aframe/src/core/system.js' {
  declare module.exports: $Exports<'aframe/src/core/system'>;
}
declare module 'aframe/src/extras/components/index.js' {
  declare module.exports: $Exports<'aframe/src/extras/components/index'>;
}
declare module 'aframe/src/extras/components/pivot.js' {
  declare module.exports: $Exports<'aframe/src/extras/components/pivot'>;
}
declare module 'aframe/src/extras/primitives/getMeshMixin.js' {
  declare module.exports: $Exports<'aframe/src/extras/primitives/getMeshMixin'>;
}
declare module 'aframe/src/extras/primitives/index.js' {
  declare module.exports: $Exports<'aframe/src/extras/primitives/index'>;
}
declare module 'aframe/src/extras/primitives/primitives.js' {
  declare module.exports: $Exports<'aframe/src/extras/primitives/primitives'>;
}
declare module 'aframe/src/extras/primitives/primitives/a-camera.js' {
  declare module.exports: $Exports<'aframe/src/extras/primitives/primitives/a-camera'>;
}
declare module 'aframe/src/extras/primitives/primitives/a-collada-model.js' {
  declare module.exports: $Exports<'aframe/src/extras/primitives/primitives/a-collada-model'>;
}
declare module 'aframe/src/extras/primitives/primitives/a-cursor.js' {
  declare module.exports: $Exports<'aframe/src/extras/primitives/primitives/a-cursor'>;
}
declare module 'aframe/src/extras/primitives/primitives/a-curvedimage.js' {
  declare module.exports: $Exports<'aframe/src/extras/primitives/primitives/a-curvedimage'>;
}
declare module 'aframe/src/extras/primitives/primitives/a-gltf-model.js' {
  declare module.exports: $Exports<'aframe/src/extras/primitives/primitives/a-gltf-model'>;
}
declare module 'aframe/src/extras/primitives/primitives/a-image.js' {
  declare module.exports: $Exports<'aframe/src/extras/primitives/primitives/a-image'>;
}
declare module 'aframe/src/extras/primitives/primitives/a-light.js' {
  declare module.exports: $Exports<'aframe/src/extras/primitives/primitives/a-light'>;
}
declare module 'aframe/src/extras/primitives/primitives/a-link.js' {
  declare module.exports: $Exports<'aframe/src/extras/primitives/primitives/a-link'>;
}
declare module 'aframe/src/extras/primitives/primitives/a-obj-model.js' {
  declare module.exports: $Exports<'aframe/src/extras/primitives/primitives/a-obj-model'>;
}
declare module 'aframe/src/extras/primitives/primitives/a-sky.js' {
  declare module.exports: $Exports<'aframe/src/extras/primitives/primitives/a-sky'>;
}
declare module 'aframe/src/extras/primitives/primitives/a-sound.js' {
  declare module.exports: $Exports<'aframe/src/extras/primitives/primitives/a-sound'>;
}
declare module 'aframe/src/extras/primitives/primitives/a-text.js' {
  declare module.exports: $Exports<'aframe/src/extras/primitives/primitives/a-text'>;
}
declare module 'aframe/src/extras/primitives/primitives/a-video.js' {
  declare module.exports: $Exports<'aframe/src/extras/primitives/primitives/a-video'>;
}
declare module 'aframe/src/extras/primitives/primitives/a-videosphere.js' {
  declare module.exports: $Exports<'aframe/src/extras/primitives/primitives/a-videosphere'>;
}
declare module 'aframe/src/extras/primitives/primitives/meshPrimitives.js' {
  declare module.exports: $Exports<'aframe/src/extras/primitives/primitives/meshPrimitives'>;
}
declare module 'aframe/src/geometries/box.js' {
  declare module.exports: $Exports<'aframe/src/geometries/box'>;
}
declare module 'aframe/src/geometries/circle.js' {
  declare module.exports: $Exports<'aframe/src/geometries/circle'>;
}
declare module 'aframe/src/geometries/cone.js' {
  declare module.exports: $Exports<'aframe/src/geometries/cone'>;
}
declare module 'aframe/src/geometries/cylinder.js' {
  declare module.exports: $Exports<'aframe/src/geometries/cylinder'>;
}
declare module 'aframe/src/geometries/dodecahedron.js' {
  declare module.exports: $Exports<'aframe/src/geometries/dodecahedron'>;
}
declare module 'aframe/src/geometries/icosahedron.js' {
  declare module.exports: $Exports<'aframe/src/geometries/icosahedron'>;
}
declare module 'aframe/src/geometries/index.js' {
  declare module.exports: $Exports<'aframe/src/geometries/index'>;
}
declare module 'aframe/src/geometries/octahedron.js' {
  declare module.exports: $Exports<'aframe/src/geometries/octahedron'>;
}
declare module 'aframe/src/geometries/plane.js' {
  declare module.exports: $Exports<'aframe/src/geometries/plane'>;
}
declare module 'aframe/src/geometries/ring.js' {
  declare module.exports: $Exports<'aframe/src/geometries/ring'>;
}
declare module 'aframe/src/geometries/sphere.js' {
  declare module.exports: $Exports<'aframe/src/geometries/sphere'>;
}
declare module 'aframe/src/geometries/tetrahedron.js' {
  declare module.exports: $Exports<'aframe/src/geometries/tetrahedron'>;
}
declare module 'aframe/src/geometries/torus.js' {
  declare module.exports: $Exports<'aframe/src/geometries/torus'>;
}
declare module 'aframe/src/geometries/torusKnot.js' {
  declare module.exports: $Exports<'aframe/src/geometries/torusKnot'>;
}
declare module 'aframe/src/geometries/triangle.js' {
  declare module.exports: $Exports<'aframe/src/geometries/triangle'>;
}
declare module 'aframe/src/index.js' {
  declare module.exports: $Exports<'aframe/src/index'>;
}
declare module 'aframe/src/lib/rStatsAframe.js' {
  declare module.exports: $Exports<'aframe/src/lib/rStatsAframe'>;
}
declare module 'aframe/src/lib/three.js' {
  declare module.exports: $Exports<'aframe/src/lib/three'>;
}
declare module 'aframe/src/shaders/flat.js' {
  declare module.exports: $Exports<'aframe/src/shaders/flat'>;
}
declare module 'aframe/src/shaders/index.js' {
  declare module.exports: $Exports<'aframe/src/shaders/index'>;
}
declare module 'aframe/src/shaders/ios10hls.js' {
  declare module.exports: $Exports<'aframe/src/shaders/ios10hls'>;
}
declare module 'aframe/src/shaders/msdf.js' {
  declare module.exports: $Exports<'aframe/src/shaders/msdf'>;
}
declare module 'aframe/src/shaders/sdf.js' {
  declare module.exports: $Exports<'aframe/src/shaders/sdf'>;
}
declare module 'aframe/src/shaders/standard.js' {
  declare module.exports: $Exports<'aframe/src/shaders/standard'>;
}
declare module 'aframe/src/systems/camera.js' {
  declare module.exports: $Exports<'aframe/src/systems/camera'>;
}
declare module 'aframe/src/systems/geometry.js' {
  declare module.exports: $Exports<'aframe/src/systems/geometry'>;
}
declare module 'aframe/src/systems/index.js' {
  declare module.exports: $Exports<'aframe/src/systems/index'>;
}
declare module 'aframe/src/systems/light.js' {
  declare module.exports: $Exports<'aframe/src/systems/light'>;
}
declare module 'aframe/src/systems/material.js' {
  declare module.exports: $Exports<'aframe/src/systems/material'>;
}
declare module 'aframe/src/systems/shadow.js' {
  declare module.exports: $Exports<'aframe/src/systems/shadow'>;
}
declare module 'aframe/src/systems/tracked-controls.js' {
  declare module.exports: $Exports<'aframe/src/systems/tracked-controls'>;
}
declare module 'aframe/src/utils/bind.js' {
  declare module.exports: $Exports<'aframe/src/utils/bind'>;
}
declare module 'aframe/src/utils/coordinates.js' {
  declare module.exports: $Exports<'aframe/src/utils/coordinates'>;
}
declare module 'aframe/src/utils/debug.js' {
  declare module.exports: $Exports<'aframe/src/utils/debug'>;
}
declare module 'aframe/src/utils/device.js' {
  declare module.exports: $Exports<'aframe/src/utils/device'>;
}
declare module 'aframe/src/utils/entity.js' {
  declare module.exports: $Exports<'aframe/src/utils/entity'>;
}
declare module 'aframe/src/utils/forceCanvasResizeSafariMobile.js' {
  declare module.exports: $Exports<'aframe/src/utils/forceCanvasResizeSafariMobile'>;
}
declare module 'aframe/src/utils/index.js' {
  declare module.exports: $Exports<'aframe/src/utils/index'>;
}
declare module 'aframe/src/utils/material.js' {
  declare module.exports: $Exports<'aframe/src/utils/material'>;
}
declare module 'aframe/src/utils/src-loader.js' {
  declare module.exports: $Exports<'aframe/src/utils/src-loader'>;
}
declare module 'aframe/src/utils/styleParser.js' {
  declare module.exports: $Exports<'aframe/src/utils/styleParser'>;
}
declare module 'aframe/src/utils/tracked-controls.js' {
  declare module.exports: $Exports<'aframe/src/utils/tracked-controls'>;
}
declare module 'aframe/vendor/rStats.extras.js' {
  declare module.exports: $Exports<'aframe/vendor/rStats.extras'>;
}
declare module 'aframe/vendor/rStats.js' {
  declare module.exports: $Exports<'aframe/vendor/rStats'>;
}
declare module 'aframe/vendor/VRControls.js' {
  declare module.exports: $Exports<'aframe/vendor/VRControls'>;
}
declare module 'aframe/vendor/VREffect.js' {
  declare module.exports: $Exports<'aframe/vendor/VREffect'>;
}
declare module 'aframe/vendor/wakelock/util.js' {
  declare module.exports: $Exports<'aframe/vendor/wakelock/util'>;
}
declare module 'aframe/vendor/wakelock/wakelock.js' {
  declare module.exports: $Exports<'aframe/vendor/wakelock/wakelock'>;
}
